varSet <- c(
  # Demongraphic
  "ODATEDW","OSOURCE","STATE","ZIP","PVASTATE","DOB","RECINHSE","MDMAUD","DOMAIN","AGE","HOMEOWNR","CHILD03","CHILD07","CHILD12","CHILD18","NUMCHLD","INCOME","GENDER","WEALTH1","HIT",
  # Donor interests
  "COLLECT1","VETERANS","BIBLE","CATLG","HOMEE","PETS","CDPLAY","STEREO","PCOWNERS","PHOTO","CRAFTS","FISHER","GARDENIN","BOATS","WALKER","KIDSTUFF","CARDS","PLATES",
  # PEP start RFA status
  "PEPSTRFL",
  # Summary var of promotion history
  "CARDPROM","MAXADATE","NUMPROM","CARDPM12","NUMPRM12",
  # summary var of giving history
  "RAMNTALL","NGIFTALL","CARDGIFT","MINRAMNT","MAXRAMNT","LASTGIFT","LASTDATE","FISTDATE","TIMELAG","AVGGIFT",
  # ID & target
  "CONTROLN","TARGET_B","TARGET_D","TARGET_D2","HPHONE_D",
  # RFA (Recency/Frequency/Donation Amount)
  "RFA_2F","RFA_2A","MDMAUD_R","MDMAUD_F","MDMAUD_A",
  # Others
  "CLUSTER2","GEOCODE2"
)